### ISSUE TITLE
Updating D5005 for OFS

### ISSUE THREAD

**Issue by wespiard** [OFS/ofs-d5005#1]
I am working on getting a D5005 working using the [newest release of OFS (2022.3)](https://github.com/OFS/ofs-d5005/releases/tag/ofs-d5005-1.0.1). The D5005 in questions was last used with Acceleration Stack 2.0.1.

I started by following [these instructions](https://github.com/OFS/ofs.github.io/blob/main/docs/hw/d5005/user_guides/ug_qs_ofs_d5005/ug_qs_ofs_d5005.md#70-programming-the-ofs-fim-and-bmc) to update the FIM and BMC. After this, when I built the `host_chan_mmio` test, but when I try to load the generated bitstream, I get a `No suitable PAC found.` error.

Here is the output of `fpgainfo fme`:
```bash
❯ sudo fpgainfo fme
Intel FPGA Programmable Acceleration Card D5005
Board Management Controller, MAX10 NIOS FW version: 2.0.13
Board Management Controller, MAX10 Build version: 2.0.8
//****** FME ******//
Object Id                        : 0xEF00000
PCIe s:b:d.f                     : 0000:04:00.0
Vendor Id                        : 0x8086
Device Id                        : 0xBCCE
SubVendor Id                     : 0x8086
SubDevice Id                     : 0x138D
Socket Id                        : 0x00
Ports Num                        : 01
Bitstream Id                     : 0x401000287428628
Bitstream Version                : 4.0.1
Pr Interface Id                  : d51533ad-aee6-5dab-80fb-a44bbf579b68
Boot Page                        : user
```

The main difference I see is the MAX10 Build version for me is 2.0.8 vs. 2.0.13. I received a BMC update image from an Intel contact, and followed [these instructions](https://github.com/OFS/ofs.github.io/blob/main/docs/hw/d5005/user_guides/ug_qs_ofs_d5005/ug_qs_ofs_d5005.md#72-programming-the-bmc) to update it. The `Object Id` is also different; not sure if that is important or not.

After building the `host_chan_mmio` example using the PR `-p` build, and trying to load the bitstream, this is the error I get:
```bash
❯ sudo fpgasupdate host_chan_mmio.gbs
[2023-05-02 13:37:43.24] [ERROR   ] No suitable PAC found.
```

Here is the kernel version:
```bash
❯ uname -r
5.15.92-dfl
```

Please let me know if there is anymore information I can provide.

**Comment by rweight** [comment]
Can you check lspci to verify that the card is visible to the PCI subsystem? lspci | grep accel

If lspci shows the card, then check to see if the drivers are loading: lsmod | grep dfl

If the card does not show, I would power-cycle the machine to see if that brings the card back

**Comment by wespiard** [comment]
Hey @rweight, thanks for the reply!

The `fpgainfo fme` output in my post should show the card is recognized. 

```bash
❯ lspci | grep accel
04:00.0 Processing accelerators: Intel Corporation Device bcce (rev 01)
```

```bash
❯ lsmod | grep dfl
spi_altera_dfl         20480  0
uio_dfl                20480  0
spi_altera_core        16384  1 spi_altera_dfl
uio                    20480  1 uio_dfl
dfl_fme_region         20480  0
dfl_fme_mgr            20480  1
dfl_fme_br             16384  0
dfl_emif               16384  0
dfl_afu                36864  0
dfl_fme                49152  0
dfl_pci                20480  0
dfl                    40960  8 dfl_pci,s10hssi,uio_dfl,dfl_fme,dfl_fme_br,dfl_afu,spi_altera_dfl,dfl_emif
fpga_region            20480  3 dfl_fme_region,dfl_fme,dfl
fpga_bridge            20480  4 dfl_fme_region,fpga_region,dfl_fme,dfl_fme_br
fpga_mgr               24576  4 dfl_fme_region,fpga_region,dfl_fme_mgr,dfl_fme
```

Also, I am able to use the `fpgasupdate` and `rsu` utilities, which is how I tried to update the BMC and FIM.

**Comment by wespiard** [comment]
I got it working by re-building the base FIM and separately building a PR tree after that. So I must have just done something wrong the first time. 

I'm still not sure why my MAX10 Build version is 2.0.8 instead of 2.0.13, though. Does that matter?

**Comment by rweight** [comment]
I'm hoping someone else will chime in as I'm not sure which BMC image/version you should have. If you have an image file for the 2.0.13 BMC image, you should be able to update to that version using fpgasupdate.

**Comment by wespiard** [comment]
Thanks for the reply. I can ask the Intel rep that sent me the image if they know of a newer version. The only BMC image I have results in the versions I showed above. This is after using `fpgasupdate` and `rsu`.

**Comment by cohensus** [comment]
Hi Wesley,
Can you provide us with your email address at our OFS github email address: ofs.github@intel.com, so we can provide the latest BMC binary?  Thanks!

**Comment by wespiard** [comment]
I tried sending an email, but I got an "undeliverable" reply. 

The status response was "550 #5.1.0 Address rejected"

**Comment by cohensus** [comment]
Can you do the same and try: ofs.marketing@intel.com

**Comment by wespiard** [comment]
That one seems to have worked. Sent the email.

**Comment by sbob84** [comment]
Hi, I'm having the same issue, got stuck at loading the result bitstream, sent the email.

**Comment by wespiard** [comment]
I'm going to close this issue, as the original problem was resolved.

**Comment by cohensus** [comment]
Thanks Wes!
